using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TDPoolingData
{

    public static Dictionary<string, TDPoolingData> dictPooledObjects = new Dictionary<string, TDPoolingData>()
    {
        {  "GroundSparkle" , new TDPoolingData(12) },
        {  "FungalColumn" , new TDPoolingData(25) },
        {  "SingleAfterImagePrefab" , new TDPoolingData(12) },
        {  "GroundStompEffect2x" , new TDPoolingData(12) },
        {  "SimpleFireEffect" , new TDPoolingData(18) },
        {  "EnemyTargeting" , new TDPoolingData(40) },
        {  "ShadowTrap" , new TDPoolingData(35) },
        {  "IceGroundTile" , new TDPoolingData(25) },
        {  "ShadowTrapPlayer" , new TDPoolingData(18) },
        {  "LeafPoof" , new TDPoolingData(15) },
        {  "PlayerTargeting" , new TDPoolingData(18) },
        {  "CombatLogDivider" , new TDPoolingData(40) },
        {  "SmokePoof" , new TDPoolingData(40) },

        {  "GreenSmokePoof" , new TDPoolingData(20) },
        {  "KunaiImpactEffect" , new TDPoolingData(27) },
        {  "KunaiImpactSystem" , new TDPoolingData(10) },
        {  "ShadowSpikeAttack" , new TDPoolingData(50) },
        {  "ShadowPierceAttack" , new TDPoolingData(15) },
        {  "IceGrowAttack2x" , new TDPoolingData(60) },
        {  "SmallIceBlockPlayer" , new TDPoolingData(30) },
        {  "SmallIceBlock" , new TDPoolingData(30) },
        {  "IceTrap1" , new TDPoolingData(24) },
        {  "BluePotionSpinEffect" , new TDPoolingData(14) },
        {  "LightningStrikeEffect" , new TDPoolingData(25) },
        {  "DialogButtonThreeColumn" , new TDPoolingData(8) }, // this doesn't appear to be pooling at all
        {  "DialogButtonWithImage" , new TDPoolingData(8) }, // this doesn't appear to be pooling at all
        {  "AcidExplosion" , new TDPoolingData(15) },
        {  "SmallExplosionEffect" , new TDPoolingData(15) },
        {  "WaterExplosion" , new TDPoolingData(10) },
        {  "FervirClawEffectSystem" , new TDPoolingData(20) },
        {  "DirtParticleExplosion", new TDPoolingData(25)},        
        {  "FervirClawEffect" , new TDPoolingData(40) },
        {  "FervirBuffSilent" , new TDPoolingData(8) },
        {  "AcidSplash" , new TDPoolingData(60) },
        {  "PoisonCloud" , new TDPoolingData(18) },
        {  "Sparkle1" , new TDPoolingData(25) },
        {  "Sparkle2" , new TDPoolingData(25) },
        {  "Sparkle3" , new TDPoolingData(25) },
        {  "Sparkle4" , new TDPoolingData(25) },
        {  "Sparkle5" , new TDPoolingData(25) },
        {  "Sparkle6" , new TDPoolingData(25) },
        {  "FireBurst" , new TDPoolingData(25) },
        {  "FireBurstBlue" , new TDPoolingData(15) },		
        {  "ArrowRain" , new TDPoolingData(10) },
        {  "DirectionIndicator" , new TDPoolingData(15) },
        {  "GreenWindEffect" , new TDPoolingData(16) },
        {  "InstantLaserEffect" , new TDPoolingData(10) },
        {  "ChargingSkillParticles" , new TDPoolingData(10) },
        {  "ItemPickupBox" , new TDPoolingData(10) }, // Is this being pooled?
        {  "GoldAura" , new TDPoolingData(10) },
        {  "PokerCard" , new TDPoolingData(12) },
        {  "Thorns2_Dimmer" , new TDPoolingData(20) },
        {  "BlingEffect" , new TDPoolingData(12) },
        {  "DefenseUpEffect" , new TDPoolingData(10) },
        {  "AttackUpEffect" , new TDPoolingData(10) },
        {  "TerrainTile" , new TDPoolingData(25) }, // This may hitch a bit on map change but THAT isn't a problem.
        {  "TransLayer" , new TDPoolingData(2300) },
        {  "TransparentStairs" , new TDPoolingData(2000) },
        {  "HealthBar" , new TDPoolingData(80) },
        {  "WaterPlank" , new TDPoolingData(15) },
        {  "MudTile" , new TDPoolingData(500) },
        {  "MudExplosion" , new TDPoolingData(50) },
        {  "CrystalVine" , new TDPoolingData(12) },
        // Stuff that really only needs a couple prefabs, less than default!
        {  "WallJump" , new TDPoolingData(3) },
        {  "GrowEffect" , new TDPoolingData(3) },
        {  "MeteorEffect" , new TDPoolingData(10) },
        {  "EnergyMeteor" , new TDPoolingData(24) },
        {  "HemorrhageEffect" , new TDPoolingData(3) },
        {  "MediumRockEffect" , new TDPoolingData(2) },
        {  "ProjectileImpactEffect" , new TDPoolingData(3) },
        {  "SummonVineEffect" , new TDPoolingData(2) },
        {  "FireBreathSFX" , new TDPoolingData(3) },
        {  "BurningBlueFireLoop" , new TDPoolingData(12) },
        {  "LightningStormSFX" , new TDPoolingData(3) },
        {  "SmiteEvilEffect" , new TDPoolingData(3) },
        {  "HundredCrackFist" , new TDPoolingData(3) },
        {  "FlurryOfPunches" , new TDPoolingData(3) },
        {  "FrostArrowEffect" , new TDPoolingData(3) },
        {  "FervirGrandRecovery" , new TDPoolingData(3) },
        {  "BellTingEffect" , new TDPoolingData(2) },
        {  "FervirBonkEffect" , new TDPoolingData(2) },
        {  "ShurikenTossEffect" , new TDPoolingData(3) },
        {  "VortexSound" , new TDPoolingData(2) },
        {  "BlackPotion" , new TDPoolingData(2) },
        {  "AutoBarrierEffect" , new TDPoolingData(2) },
        {  "LargeArrowEffect" , new TDPoolingData(3) },
        {  "SpiderWebEffect" , new TDPoolingData(3) },
        {  "LargeRockEffect2x" , new TDPoolingData(2) },
        {  "AcidCloudSFX" , new TDPoolingData(3) },
        {  "GreenPotionSpinEffect" , new TDPoolingData(2) },
        {  "BigCureSFX" , new TDPoolingData(3) },
        {  "ArtillerySFX" , new TDPoolingData(3) },
        {  "SndMirageEffect" , new TDPoolingData(3) },
        {  "WaterSplashSFX" , new TDPoolingData(3) },
        {  "MindControl" , new TDPoolingData(3) },
        {  "EnterWaterSplash" , new TDPoolingData(3) },
        {  "JumpAndImpactSFX" , new TDPoolingData(3) },
        {  "TeleportUp" , new TDPoolingData(3) },
        {  "Wildling" , new TDPoolingData(2) },
        {  "Edge Thane" , new TDPoolingData(2) },
        {  "Soulkeeper" , new TDPoolingData(2) },
        {  "Husyn" , new TDPoolingData(2) },
        {  "Gambler" , new TDPoolingData(2) },
        {  "Hunter" , new TDPoolingData(2) },
        {  "MartialArtist" , new TDPoolingData(2) },
        {  "Paladin" , new TDPoolingData(2) },
        {  "Spellshaper" , new TDPoolingData(2) },
        {  "SwordDancer" , new TDPoolingData(2) },
        {  "LNY_SwordDancer" , new TDPoolingData(2) },
        {  "Floramancer" , new TDPoolingData(2) },
        {  "Brigand" , new TDPoolingData(2) },
        {  "JobShara" , new TDPoolingData(2) },
        {  "RunicCrystal" , new TDPoolingData(3) },
        {  "TeleportDown" , new TDPoolingData(2) },
        {  "FinalBossPhase2" , new TDPoolingData(2) },
        {  "Panthrox" , new TDPoolingData(2) },
        {  "FemaleSoundEmanation" , new TDPoolingData(3) },
        {  "EnduranceAura1" , new TDPoolingData(2) },
        {  "EnduranceAura2" , new TDPoolingData(2) },
        {  "EnduranceAura3" , new TDPoolingData(2) },
        {  "MightAura1" , new TDPoolingData(2) },
        {  "MightAura2" , new TDPoolingData(2) },
        {  "MightAura3" , new TDPoolingData(2) },
        {  "SpiritAura1" , new TDPoolingData(2) },
        {  "SpiritAura2" , new TDPoolingData(2) },
        {  "SpiritAura3" , new TDPoolingData(2) },
        {  "GiantFistAttack" , new TDPoolingData(3) },
        {  "FlowAura" , new TDPoolingData(3) },
        {  "GenericTurnedThrustAttack" , new TDPoolingData(3) },
        {  "SmallArrowEffect" , new TDPoolingData(3) },
        {  "PowerEnergyProjectile" , new TDPoolingData(3) },
        {  "WoodArrowEffect" , new TDPoolingData(3) },
        {  "Portal" , new TDPoolingData(2) },
        {  "AltPortal" , new TDPoolingData(2) },
        {  "FlowShatterParticles" , new TDPoolingData(3) },
        {  "VoidShatterParticles" , new TDPoolingData(3) },
        {  "NPCRaccoonMerchant2" , new TDPoolingData(2) },
        {  "NPCRaccoonMerchant3" , new TDPoolingData(2) },
        {  "NPCHalfDemon" , new TDPoolingData(2) },
        {  "NPCRaccoonMerchant4" , new TDPoolingData(2) },
        {  "NPCRaccoonMerchant5" , new TDPoolingData(2) },
        {  "NPCRaccoonMerchant6" , new TDPoolingData(2) },
        {  "NPCCatBirdMerchant" , new TDPoolingData(2) },
        {  "NPCRaccoonMerchant" , new TDPoolingData(2) },
        {  "NPCBanker" , new TDPoolingData(2) },
        {  "NPCSharkGuy" , new TDPoolingData(2) },
        {  "NPCCatBirdMerchant2" , new TDPoolingData(2) },
        {  "WiseWoman" , new TDPoolingData(2) },
        {  "NPCTurtle" , new TDPoolingData(2) },
        {  "NPCMonsterRancher" , new TDPoolingData(2) },
        {  "NPCFrogFarmer" , new TDPoolingData(2) },
        {  "NPCBigBlacksmith" , new TDPoolingData(2) },
        {  "NPCPainter" , new TDPoolingData(2) },
        {  "NPCMoonRabbit" , new TDPoolingData(2) },
        {  "NPCCampfire2" , new TDPoolingData(2) },
        {  "NPCPeebis" , new TDPoolingData(2) },
        {  "NPCGoldfrog" , new TDPoolingData(2) },
        {  "MonsterFriendlyBandit" , new TDPoolingData(2) },
        {  "FriendlyBanditLady" , new TDPoolingData(2) },
        {  "NPCSharkGuy2" , new TDPoolingData(2) },
        {  "ItemWorldMachine" , new TDPoolingData(2) },
        {  "NPCTinkerer" , new TDPoolingData(2) },
        {  "SkirmisherEffect" , new TDPoolingData(3) },
        {  "NPCWeaponMaster" , new TDPoolingData(2) },
        {  "NPCMonsterRancher2" , new TDPoolingData(2) },
        {  "MonsterSidewaysRockGolem" , new TDPoolingData(2) },
        {  "ReflectEffect" , new TDPoolingData(3) },
        {  "NPCBigBlacksmith2" , new TDPoolingData(2) },
        {  "FrozenScientist" , new TDPoolingData(2) },
        {  "FrozenScientistHalf" , new TDPoolingData(2) },
        {  "SnowMachine" , new TDPoolingData(2) },
        {  "NPCRubyWitch" , new TDPoolingData(2) },
        {  "PinkSlime" , new TDPoolingData(2) },
        {  "NPCHusyn" , new TDPoolingData(2) },
        {  "NPCHalfDemon2" , new TDPoolingData(2) },
        {  "PlayerRootedEffect" , new TDPoolingData(2) },
        {  "MonsterShara" , new TDPoolingData(2) },
        {  "FallenShara" , new TDPoolingData(2) },
        {  "NPCFoodCart" , new TDPoolingData(2) },
        {  "NPCHerbalist" , new TDPoolingData(2) },
        {  "NPCLostMagician" , new TDPoolingData(2) },
        {  "NPCCasie" , new TDPoolingData(2) },
        {  "StarshardEffect" , new TDPoolingData(2) },
        {  "TeleportUpSilent" , new TDPoolingData(2) },
        {  "FadeAwayParticles" , new TDPoolingData(2) },
        {  "MassiveShatterParticles" , new TDPoolingData(2) },
        {  "PandoraBoxOpen" , new TDPoolingData(2) },
        {  "PandoraChestAnimated" , new TDPoolingData(2) },
        {  "SkullAltar" , new TDPoolingData(1) },
        {  "Electrocute" , new TDPoolingData(2) },
        {  "WoodBreak" , new TDPoolingData(2) },
        {  "Campfire" , new TDPoolingData(2) },
        {  "CampfireCenter" , new TDPoolingData(2) },
        {  "CampfireBG" , new TDPoolingData(2) },
        {  "ShatterBreak" , new TDPoolingData(2) },
        {  "Kitchen" , new TDPoolingData(2) },
        {  "OriOre" , new TDPoolingData(2) },
        {  "SuperChestOpen" , new TDPoolingData(2) },
        {  "SuperChestClosed" , new TDPoolingData(2) },
        {  "TechCube" , new TDPoolingData(2) },
        {  "AcidTile" , new TDPoolingData(15) },
        {  "BurningFireLoop" , new TDPoolingData(30) },
        {  "SwingingVine" , new TDPoolingData(20) },
        {  "GhostCursorSparkles" , new TDPoolingData(20) },
        {  "EnergyPowerup" , new TDPoolingData(15) },
        {  "StaminaPowerup" , new TDPoolingData(15) },
        {  "ChildShara" , new TDPoolingData(2) },
        {  "DominatorHead" , new TDPoolingData(2) },
        {  "Tree1" , new TDPoolingData(12) },
        {  "Tree3" , new TDPoolingData(12) },
        {  "Tree5" , new TDPoolingData(12) },
        {  "Tree8" , new TDPoolingData(12) },
        {  "Tree7" , new TDPoolingData(12) },
    };

    public int quantityToPool;
    public bool doNotReparent;

    public TDPoolingData(int qty, bool noReparent = false)
    {
        quantityToPool = qty;
        doNotReparent = noReparent;
    }

}
